### ISSUE TITLE
Nameplate icon glow bug - massive green square obstructs visuals

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DeadlyBossMods#1413]
**Describe the bug**
Nameplate icons frequently, but not always, produce a massive green square that quickly disappears. The error is inconsistent but can usually be reproduced. If the massive green square appears, it will very quickly shrink down to a normal size.

**Do you have an error log of what happened?**
None at the moment, but willing to run if needed.

**To Reproduce**
1. Enter Waterworks delve on any difficulty.
2. Clear until you find a Kobold Taskfinder
3. Let the Kobold Taskfinder cast Blazing Wick.

**Screenshots**
![WoWScrnShot_120824_234444](https://github.com/user-attachments/assets/74cbcb2c-fd64-4ca6-b29c-e99df310c73b)
![WoWScrnShot_120824_234904](https://github.com/user-attachments/assets/38dec558-155c-4272-a5bd-e33389f15f6b)
![WoWScrnShot_120824_234921](https://github.com/user-attachments/assets/3a226ae5-5b83-4f93-b809-e453454768d6)
![WoWScrnShot_120824_234923](https://github.com/user-attachments/assets/1f0e1be5-0a3c-406a-8d2b-2b545cd30078)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Only DBM as well as BugSack and BugGrabber were enabled.

**Which version of DeadlyBossMods are you using?**
Core 11.0.34-8 alpha
Dungeons r173 release

**Was it working in a previous version? If yes, which was the last good one?**
Do not recall. Only noticed today upon a different user's report.

**Additional context**
Tested in Waterworks delve.

**Comment by MysticalOS** [comment]
I've done that dozens of times, never seen the bug. so I'd say it's not reproducible, therefor this will be marked low priority and be ignored for now

**Comment by MysticalOS** [comment]
I will tag @cont1nuity though but me attempting to fix something that never happens to me would just be a blind waste of time

**Comment by cont1nuity** [comment]
@jungheeMW are you using Masque?

**Comment by MysticalOS** [comment]
Try with 11.0.34-13-g3ee1480 or later

**Comment by jungheeMW** [comment]
LUA error upon logging in: https://pastebin.com/VVQBKaJg
Tested with only DBM, BugGrabber, BugSack, Simple Addon Manager.

**Comment by jungheeMW** [comment]
Another LUA error occuring moments after loading into delve, running in the same conditions as previous
https://pastebin.com/NfD8jpiQ

**Comment by MysticalOS** [comment]
this wouldn't be from change I made

**Comment by MysticalOS** [comment]
I'm gonna guess PR i merged from paul broke DBM core

**Comment by MysticalOS** [comment]
Fixed that error, was entirely unrelated to this issue and was related to fact that DBM:IsSeasonal can't be called in localization since it loads before that function does.

**Comment by jungheeMW** [comment]
I reverted to Core 11.0.34-13-g3ee1480 to test the fixes and the issues still persist (intermittently). It might be specific to this delve or mob.

Tested with only the following addons enabled:
BugGrabber
BugSack
Simple Addon Manager

**Comment by MysticalOS** [comment]
https://github.com/DeadlyBossMods/DeadlyBossMods/issues/1413#issuecomment-2526597075

**Comment by jungheeMW** [comment]
Retested on Core 11.0.34-21 alpha, which did not affect the results (original reported problem of massive green square still exists, and is intermittent).

**Comment by MysticalOS** [comment]
Try with https://github.com/DeadlyBossMods/DeadlyBossMods/commit/b064d028aff6e3cf2a8956dd959a7c6538ec3147 or newer

**Comment by jungheeMW** [comment]
Tested https://github.com/DeadlyBossMods/DeadlyBossMods/commit/b064d028aff6e3cf2a8956dd959a7c6538ec3147, original reported issue still persists.
Only running DBM, BugSack, BugGrabber, Simple Addon Manager.

**Comment by MysticalOS** [comment]
Went into delve and just can't reproduce this issue. i'm not saying it doesn't exist, but to even perceive it you'd have to play game in ultra slow motion. I'm beginning to think this is just only an issue at low fps or even just a digital foundry type issue where they do 8x zoom on a pixel to show how that pixel is jagged if you put your face against screen and fixate on it.

I think for the 2 users in entire world that have this issue, can just turn the glow off

**Comment by MysticalOS** [comment]
i've identified the bug finally
it's a bug in libcustomglow
reason I wasn't having bug is I'm not using default settings. the bug is in "proc" effect
i'm using button

I'm gonna change dbm default to button for now and force reset defaults for all users. and put a ticket in for proc glow issue with lib maybe

**Comment by MysticalOS** [comment]
https://github.com/DeadlyBossMods/DeadlyBossMods/commit/948fb06630200a83189b4d9e69d1e432a40fd91f
works around issue for now, but the TL/DR, just go into nameplate options and change cast glow from proc to button (or update dbm and it'll be force changed for you)
