### ISSUE TITLE
Shadow-Lord Iskar DBM Core Error

### ISSUE THREAD

**Issue by reale411** [DeadlyBossMods/DeadlyBossMods#522]
DBM-Core-9.0.22-3-g136beff.zip
DBM-Draenor-r54.zip

Happens twice during encounter, solo on Mythic:

Message: Interface\AddOns\DBM-Core\DBM-Core.lua:10423: attempt to compare nil with number
Time: Wed Mar 10 16:49:07 2021
Count: 2
Stack: Interface\AddOns\DBM-Core\DBM-Core.lua:10423: attempt to compare nil with number
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:10423: in function `Play'
[string "@Interface\AddOns\DBM-HellfireCitadel\Iskar.lua"]:208: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:892: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:879>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:892: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:879>

Locals: self = <table> {
 type = "count"
 spellId = 181912
 option = "SpecWarn181912count"
 text = "Focused Blast! (%s)"
 icon = 1117885
 flash = 2
 combinedcount = 0
 mod = <table> {
 }
 announceType = "count"
 combinedtext = <table> {
 }
 sound = true
 spellName = "Focused Blast"
}
name = "gather"
customPath = nil
always = false
voice = "VEM"
(*temporary) = nil
(*temporary) = 11
(*temporary) = "mythic"
(*temporary) = false
(*temporary) = nil
(*temporary) = "attempt to compare nil with number"
DBM = <table> {
 CHAT_MSG_ADDON_LOGGED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:5395
 CopyAllModOption = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3703
 FindScenarioIDs = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7657
 PLAY_MOVIE = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7703
 FindDungeonMapIDs = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7629
 GetUnitIdFromGUID = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3394
 CopyProfile = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:2029
 CHAT_MSG_MONSTER_EMOTE = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:5986
 CHAT_MSG_WHISPER = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7367
 SendPVPTimers = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7178
 DeleteProfile = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:2046
 DungeonMusic = <table> {
 }
 ShowUpdateReminder = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:5538
 lastAntiSpamFLASH = 105097.375000
 PLAYER_REGEN_DISABLED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:5777
 FireEvent = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1674
 CreateModLocalization = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:12795
 SCENARIO_COMPLETED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:4082
 IsEnabled = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7447
 GetMyPlayerInfo = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3233
 Capitalize = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7557
 ADDON_LOADED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1370
 IconNumToTexture = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7623
 BattleMusic = <table> {
 }
 ShowRaidIDRequestResults = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:5248
 INSTANCE_GROUP_SIZE_CHANGED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3149
 GetBossUnitId = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3377
 AddDefaultOptions = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3463
 UPDATE_MOUSEOVER_UNIT = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:4419
 InfoFrame = <table> {
 }
 FilterRaidBossEmote = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1208
 RequestTimers = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7080
 UPDATE_BATTLEFIELD_STATUS = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:4060
 CheckNearby = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3424
 CHAT_MSG_MONSTER_YELL = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:5978
 LFG_PROPOSAL_SHOW = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3992
 ReleaseRevision = 2021030

**Comment by MysticalOS** [comment]
Fixed, thanks.

**Comment by reale411** [comment]
Thank you!

**Comment by reale411** [comment]
Hello,

This is still happening as of today: DBM-Core-9.0.30 / DBM-Draenor-r54

Message: Interface\AddOns\DBM-Core\DBM-Core.lua:10476: attempt to compare nil with number
Time: Wed Jun 16 20:52:29 2021
Count: 3
Stack: Interface\AddOns\DBM-Core\DBM-Core.lua:10476: attempt to compare nil with number
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:10476: in function `Play'
[string "@Interface\AddOns\DBM-HellfireCitadel\Iskar.lua"]:208: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:895: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:882>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:895: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:882>

Locals: self = <table> {
 type = "count"
 spellId = 181912
 option = "SpecWarn181912count"
 text = "Focused Blast! (%s)"
 icon = 1117885
 flash = 2
 combinedcount = 0
 mod = <table> {
 }
 announceType = "count"
 combinedtext = <table> {
 }
 sound = true
 spellName = "Focused Blast"
}
name = "gather"
customPath = nil
always = false
voice = "VEM"
(*temporary) = nil
(*temporary) = 11
(*temporary) = "mythic"
(*temporary) = false
(*temporary) = nil
(*temporary) = "attempt to compare nil with number"
DBM = <table> {
 CHAT_MSG_ADDON_LOGGED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:5409
 CopyAllModOption = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3717
 FindScenarioIDs = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7694
 PLAY_MOVIE = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7740
 FindDungeonMapIDs = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7666
 GetUnitIdFromGUID = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3408
 CopyProfile = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:2033
 CHAT_MSG_MONSTER_EMOTE = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:6000
 CHAT_MSG_WHISPER = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7404
 SendPVPTimers = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7215
 DeleteProfile = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:2050
 DungeonMusic = <table> {
 }
 ShowUpdateReminder = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:5552
 lastAntiSpamFLASH = 282433.939000
 PLAYER_REGEN_DISABLED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:5791
 FireEvent = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1678
 CreateModLocalization = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:12849
 SCENARIO_COMPLETED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:4096
 IsEnabled = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7484
 GetMyPlayerInfo = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3247
 Capitalize = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7594
 ADDON_LOADED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1373
 IconNumToTexture = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7660
 BattleMusic = <table> {
 }
 ShowRaidIDRequestResults = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:5262
 INSTANCE_GROUP_SIZE_CHANGED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3163
 GetBossUnitId = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3391
 AddDefaultOptions = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3477
 UPDATE_MOUSEOVER_UNIT = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:4433
 InfoFrame = <table> {
 }
 FilterRaidBossEmote = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1211
 RequestTimers = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:7117
 UPDATE_BATTLEFIELD_STATUS = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:4074
 CheckNearby = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3438
 CHAT_MSG_MONSTER_YELL = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:5992
 LFG_PROPOSAL_SHOW = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:4006
 ReleaseRevision = 2021061

**Comment by QartemisT** [comment]
Resolving this now by pushing a new release for DBM-WoD, as one was never created after this was patched.

**Comment by reale411** [comment]
Thanks again, good hunting!
